variables:
  VersionSuffix: -rc.1-alpha.$(Build.BuildNumber)

jobs:
- job: Setup
  steps:
    - pwsh: >
          $path = "$(Build.Repository.LocalPath)\version.txt";
          Write-Host "Grabbing version from: $path";

          if(![System.IO.File]::Exists($path)){
            Write-Error "File not found!";
          }

          $version = (Get-Content $path).Trim();
          Write-Host "Version found: $version";

          try
          {
            [System.Management.Automation.SemanticVersion]::Parse($version);
          }
          catch
          {
            Write-Error "'$version' is an invalid SemVer version"
          }

          Write-Host "##vso[task.setvariable variable=BaseVersion;isOutput=true]$version";
      failOnStderr: true
      name: buildBaseVersion
      displayName: "Verify and set BaseVersion variable"

- job: Read
  dependsOn: Setup
  variables:
    CoalesceVersion: "buh$[ dependencies.Setup.outputs['Setup.buildBaseVersion.BaseVersion'] ]cha"
  steps:
    - pwsh: Write-Host $(CoalesceVersion)