steps:
  - task: PowerShell@2
    inputs:
      targetType: inline
      pwsh: true
      failOnStderr: true
      errorActionPreference: stop
      script: >
        $path = "$(Build.Repository.LocalPath)\version.txt";
        Write-Host "Grabbing version from: $path";

        if(![System.IO.File]::Exists($path)){
          Write-Error "File not found!";
        }

        $version = (Get-Content $path).Trim();
        Write-Host "Version found: $version";

        try
        {
          [System.Management.Automation.SemanticVersion]::Parse($version);
        }
        catch
        {
          Write-Error "Invalid SemVer version"
        }

        Write-Host "##vso[task.setvariable variable=CoalesceVersion;]$version";