
steps:
  - powershell: >
      $version = Get-Content -Path version.txt;
      $version = $version.Trim();
      Write-Host "##vso[task.setvariable variable=CoalesceVersion;]$version"
      Write-Host $env:CoalesceVersion;

    displayName: "Grab CoalesceVersion env variable"