steps:
  - task: PowerShell@2
    inputs:
      targetType: inline
      pwsh: true
      script: >
        $path = "$(Build.Repository.LocalPath)\version.txt";
        Write-Host "Grabbing version from: $path";

        if(![System.IO.File]::Exists($path)){
          Write-Error "File not found!";
        }

        $version = (Get-Content $path).Trim();
        Write-Host "Version found: $version";

        if (![System.Management.Automation.SemanticVersion].TryParse($version))
        {
          Write-Error "Version provided is not a valid SemVer";
        }

        Write-Host "##vso[task.setvariable variable=CoalesceVersion;]$version";