steps:
  - script: choco install powershell-core --version 6.1.1 -y
  - powershell: Write-Host($($PSVersionTable.PSVersion))
  - powershell: >
      $path = "$(Build.Repository.LocalPath)\version.txt";
      Write-Host "Trying version path: $path";
      if(![System.IO.File]::Exists($path)){
        Write-Error "Path not found!";
      }
      $version = Get-Content $path;
      Write-Warning "Version: $version";
      $version = $version.Trim();
      Write-Warning "Version Trim: $version";
      Write-Host "##vso[task.setvariable variable=CoalesceVersion;]$version";
      Write-Warning "meh";
      Write-Warning "Env? $($env:CoalesceVersion)";

    displayName: "Grab CoalesceVersion env variable"

  - powershell: Write-Warning "Env? $($env:CoalesceVersion) or $(CoalesceVersion)";

    displayName: "eh?"