steps:
  - task: PowerShell@2
    inputs:
      targetType: inline
      pwsh: true
      script: >
        $path = "$(Build.Repository.LocalPath)\version.txt";
        Write-Host "Grabbing version from: $path";

        if(![System.IO.File]::Exists($path)){
          Write-Error "File not found!";
        }

        $version = (Get-Content $path).Trim();
        Write-Host "Version found: $version";

        #throws if not a valid SemVer
        [System.Management.Automation.SemanticVersion]($version);

        Write-Host "##vso[task.setvariable variable=CoalesceVersion;]$version";